param([ValidateSet('enemies','inventory')][string]$Group)
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$reference=@((Join-Path $root '资产\原画\bear_refined.png'),(Join-Path $root '资产\原画\v120_garden.png'))
$prompts=@{
enemies='Generate a polished production pixel game sprite atlas in EXACTLY 4 equal columns and 3 equal rows. Each cell exactly one isolated full creature centered, transparent background and safe margins. No text, no labels, no grid, no floor, no ground shadows. Use references for the exact cute warm garden pixel style, bold dark-brown outlines, clear top-down 3/4 view, readable silhouettes. Row 1: round 2 boss giant angry honey queen wasp with crown and striped abdomen; the SAME queen wasp defeated, lying on side with closed eyes and wings drooping but no gore; round 3 boss giant ancient moonlit flowering treant with glowing roots and crescent face; the SAME moon treant defeated, kneeling with dim flowers and drooping branches, no gore. Row 2: fast hostile honey wasp; red thornling charging seed with spikes; prickly hedgehog with armor leaves; purple seed caster holding seed sling. Row 3: ghostly dusk shade; blue crystal crab with frontal shield; dark spore bat firing spores; big root brute smashing wooden fences. Two bosses much larger within their cells, 8 minions visibly different from existing garden sprites, coherent lighting and pixel scale.'
inventory='Generate polished production pixel game inventory atlas in EXACTLY 4 equal columns and 4 equal rows. Each cell one centered isolated object, transparent background, large safe margins, no labels no grid no floor. Warm cute garden pixel style matching the supplied references, strong brown outlines and material highlights, very readable at 48 pixels. Row 1: honeycomb short sword; tiny hive bow with striped arrow; moon prism staff with glowing crystal; heavy root hammer with wooden head. Row 2: wasp knight headgear; flower petal mantle vest; crescent moon boots; twisting root heart charm. Row 3: nectar flask active item; thorn orb active item; tiny moon bell active item; revival flower active item. Row 4: miniature beehive turret building; reinforced garden wall building; moon lantern tower building; tall root vine tower building. Every object distinct. Exactly 16 inventory icons.'
}
$image25Script=if($env:IMAGE25_SCRIPT_PATH){$env:IMAGE25_SCRIPT_PATH}else{Join-Path $HOME '.codex\skills\image25\scripts\image25.ps1'}
if(-not(Test-Path -LiteralPath $image25Script)){throw 'Set IMAGE25_SCRIPT_PATH to the configured image25.ps1 script.'}
& $image25Script -Command edit -Image $reference -Prompt $prompts[$Group] -Size '1536x1024' -Quality high -Output (Join-Path $root ('资产\原画\v140_'+$Group+'.png'))
