param([ValidateSet('casual','garden','adventure','pajamas','spring','magic','icons','upgrades','crossbow')][string]$Group)
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$themes=@{
casual='cozy everyday couple: white bear wears tiny rose gingham dress, brown bear wears tiny cream striped shirt and mint short overalls'
garden='gardeners: white bear wears a small flower straw bonnet and pink apron, brown bear wears a small leaf straw hat and sage gardening apron'
adventure='woodland adventurers: white bear wears tiny cream explorer hood and rose capelet, brown bear wears small khaki scout cap and moss vest with tiny backpack'
pajamas='bedtime couple: white bear wears strawberry pink short pajama romper and small sleeping cap, brown bear wears moon yellow short pajama romper and small nightcap'
spring='spring blossoms: white bear wears a tiny pink petal skirt and small flower crown, brown bear wears a tiny green petal tunic and small daisy wreath'
magic='garden magic: white bear wears small rose wizard hat and short cream star cape, brown bear wears small violet wizard hat and tiny mint star cape'
}
if($Group -eq 'crossbow') {
 $prompt='ONE isolated polished pixel art game inventory icon: tiny cute STAR CROSSBOW, warm wooden handle at bottom left, bow limbs cream and honey gold, central arrow aimed upper right, star shaped brass fastener, mint leaf and small pink ribbon accents. It must be unmistakably a crossbow, NOT an embroidery needle. Same warm garden color palette as reference. Rich material highlights, clear dark brown outline, readable at 64px. Transparent background, centered with wide margins, no bear, no hands, no text no ground no shadow. Single object only.'
} elseif($Group -eq 'upgrades') {
 $prompt='Polished warm garden pixel game icon atlas, EXACTLY 4 columns and 4 rows equal cells. One centered isolated readable icon per cell, wide empty spacing, transparent background, no text no grid no labels. Same cute detailed garden style as supplied bear reference. Row 1: big wooden honey spoon melee weapon; pink HEART tipped magic wand weapon; shiny silver embroidery needle with pink thread weapon; rose petal spinning flower weapon. Row 2: strawberry heart vitality; glass bottle of warm milk with leaf; strawberry jam jar strength; mint candy attack speed. Row 3: tiny garden running boots speed; sparkling golden lucky star critical hit; leafy wooden armor shield; glowing flower pickup magnet. Row 4: tiny wrench with sprout building power; blooming large flower area boost; floral hourglass skill cooldown; intertwined pink and honey hearts couple skill. Bold dark brown outlines, cream highlights, rich material detail, vivid distinct silhouettes readable at 48px. Do not make cheap simple geometric symbols. No sprite may cross its own cell boundary.'
} elseif($Group -eq 'icons') {
 $prompt='Production pixel game UI icon atlas. EXACTLY 6 equal columns by 4 equal rows. ONE isolated centered icon per cell, TRANSPARENT background, safe margins, NO text NO letters NO labels NO grid NO floor. Crisp polished warm cute garden pixel art matching reference. Row 1 categories: crossed spoon and wand; tiny armor vest; heart pendant; consumable seed pouch; wooden turret; giant strawberry guardian. Row 2 EMPTY SLOT outlines in muted sage and brown, hollow center, each recognizable: left hand sword silhouette; right hand wand silhouette; hat silhouette; shirt silhouette; pair of boots silhouette; ring silhouette. Row 3: empty consumable pouch outline; red strawberry heart health upgrade; tender sprout with healing droplet; leaf armor shield; pink healing flower aura; repair wrench with blossom. Row 4: glowing protective bubble shield; reinforced wooden wall protection; berry projectile with motion trail; curling attacking vine; empty wooden building silhouette; golden strawberry currency coin. Icons richly detailed yet clean and readable at 48 pixels. All evenly sized.'
} else {
 $prompt='Use ONLY supplied approved bear reference as exact identity. Complete dressed CHARACTER sprites, not separate garments. Production crisp polished pixel art atlas TRANSPARENT background. EXACTLY 3 equal columns and 2 equal rows, one centered full body bear per cell, safe transparent margins, NO text NO labels NO grid NO handheld objects NO weapons NO ground shadows. Top row white Yier: front, facing right side, back. Bottom row tan Bubu: front, facing right side, back. Theme: '+$themes[$Group]+'. Preserve SAME original enormous round face, tiny ears, eyes, small mouth, blush, dark warm brown outline, giant head ~75% of body, VERY TINY body, VERY SHORT stubby arms and feet. No humanoid proportions, no longer limbs, no different faces. Yier is white with dark brown ears and little brown bow, pink cheek blush; Bubu tan with dark ear centers and honey cheeks. Outfit is fitted to existing tiny body and covers only small lower portion. Hat must not hide ears or face. Consistent costume details in all three views. Same feet baseline and same character size in each cell. Cute warm garden palette. Pixel edges are sharp, no blur. 1536x1024 canvas.'
}
$image25Script=if($env:IMAGE25_SCRIPT_PATH){$env:IMAGE25_SCRIPT_PATH}else{Join-Path $HOME '.codex\skills\image25\scripts\image25.ps1'}
if(-not(Test-Path -LiteralPath $image25Script)){throw 'Set IMAGE25_SCRIPT_PATH to the configured image25.ps1 script.'}
& $image25Script -Command edit -Image (Join-Path $root '资产\原画\bear_refined.png') -Prompt $prompt -Size '1536x1024' -Quality high -Output (Join-Path $root ('资产\原画\v130_'+$Group+'.png'))
