param([ValidateSet('characters','garden','enemies','inventory')][string]$Group)
$ErrorActionPreference='Stop'
$root=Split-Path $PSScriptRoot -Parent
$prompts=@{
characters='Use the supplied approved bear master as exact identity and proportion reference. Production pixel sprite atlas, transparent background, exactly 3 equal columns and 2 equal rows, generous transparent margins, no text no labels no ground no shadow. Top row white Yier with dark brown little ears pink blush brown tiny bow; bottom row warm tan Bubu golden blush. Each row: front facing, right side facing, back facing. Each cell exactly one complete full-body bear centered and same height. Preserve enormous round head 75 percent total height, very tiny round body, TINY stubby arms and feet, absolutely no elongated humanoid limbs. Clean crisp cute pixel art, dark warm brown outline, creamy highlights, consistent reference facial identity. The original front silhouettes must be almost identical to reference. 1536x1024 canvas.'
garden='Create a game-ready pixel atlas matching the warm cute garden palette of reference. Exactly 4 columns by 4 rows equal grid cells, one isolated centered asset per cell, transparent background, no text no labels no grid lines no shadow floor, generous spacing. Row 1: giant living strawberry guardian healthy; same giant strawberry slightly bruised; same giant strawberry moderately cracked; same giant strawberry heavily cracked. Row 2: same strawberry critical dying wilted but still recognizable; thorn wooden fence; fast seed-shooting wooden turret with leafy barrel; strawberry mortar turret with round barrel. Row 3: blue frost blossom slowing tower; pink healing fountain; cute scarecrow wearing straw hat; garden spike patch. Row 4: leafy springboard; tiny repair robot with wrench; cute vine bear trap; huge snail boss with spiral mossy shell and angry eyes. Core five states have identical silhouette scale/position with progressive leaf drooping/cracks, no gore. Detailed polished pixel-art silhouettes suitable at 64 to 96 pixels, not geometric placeholders.'
enemies='Production game sprite atlas, 4 columns by 3 rows equal grid cells. Transparent background, NO text NO labels NO ground, one centered full creature per cell with safe transparent margins. Warm cute pixel garden enemies distinct roles. Row 1: angry sprout; red beetle charger with horns; acorn spitter holding seed; mole with digging claws. Row 2: termite carpenter chewing wood; flying purple crow with berry; shield beetle with huge leaf shield facing front; explosive red mushroom. Row 3: healer mushroom with glowing green sprig; mimic slime with tiny wand; dark fog moth; parasitic purple vine leech. Detailed charming dark-brown outlines and readable warm pixel palette compatible with reference bears. Distinct silhouettes, not simplistic geometric placeholders.'
inventory='Game-ready polished pixel icon atlas. Exactly 6 columns and 6 rows equal grid, transparent background no text no labels no grid no shadows, one centered isolated object per cell generous margins, cute warm garden style matching reference. Row 1: strawberry bouncing slingshot; fast gardening shears; returning garden shovel; honey spray gun; bubble wand; star summoning wand. Row 2: huge radish hammer; red thread spool wand; crescent energy sword; flame sunflower gun; magnet cap; mechanic goggles. Row 3: first-hit flower shield helmet; thorn vest; spring dash boots; mint running shoes; glowing purple skill stone; lucky four-leaf charm. Row 4: paired heart pendant; shockwave shell pendant; hovering star familiar; firefly lantern; coin purse; golden probability cloud with no solid outline (time stop item). Row 5: huge strawberry bomb; healing seed pouch; instant wooden fence kit; explosive decoy doll; homeward berry stone; suction magnet device. Row 6: mirror glove copying weapon; icy hourglass; merchant reroll dice; rideable rocket; slippery banana peel; gardening toolbox. Clear rich pixel material details with brown outline, gentle palette and tiny highlights. All icons equally legible at 48px.'
}
$image25Script=if($env:IMAGE25_SCRIPT_PATH){$env:IMAGE25_SCRIPT_PATH}else{Join-Path $HOME '.codex\skills\image25\scripts\image25.ps1'}
if(-not(Test-Path -LiteralPath $image25Script)){throw 'Set IMAGE25_SCRIPT_PATH to the configured image25.ps1 script.'}
& $image25Script -Command edit -Image (Join-Path $root '资产\原画\bear_refined.png') -Prompt $prompts[$Group] -Size '1536x1024' -Quality high -Output (Join-Path $root ('资产\原画\v120_'+$Group+'.png'))
